[package]
name = "pethotel-api"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.3", features = ["postgres", "chrono"] }
actix-web = "4"
dotenv = "0.15"
diesel_migrations = "2.2.0"
serde = "1.0.217"
chrono = "0.4.39"
bcrypt = "0.17.0"
jsonwebtoken = "9.3.0"
time = "0.3"
lazy_static = "1.5.0"