services:
  postgres:
    image: postgres:latest
    container_name: postgres_actix_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:latest
    container_name: postgres_actix_db_test
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${DB_TEST_NAME}
    ports:
      - "${DB_TEST_PORT}:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql_test/data
  app:
    build:
      dockerfile: Dockerfile
    image: henrquedev/actix-jwt-api-app:tests
    container_name: actix_jwt_api
    restart: always
    depends_on:
      - postgres
    ports:
      - "587:587"
      - "${APP_PORT}:8080"
    command: ["./target/release/${APP_NAME}"]

volumes:
  postgres_data:
  postgres_test_data:
