services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
    container_name: rust_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "${APP_PORT}:8080"
    command: ["./pethotel-api"]

volumes:
  postgres_data:
